name: Publish
on:
  # Trigger on every tag
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Release
    strategy:
      matrix:
        target: ['linux-x64', 'win-x64', 'win-x32']
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v1

      # Setup .NET 5.0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # Clean the output folder
      - name: Clean
        run: rm -rf ./release.tar.gz ./release

      # Publish the .NET project
      - name: Publish release
        run: dotnet publish -c Release -r "${{ matrix.target }}" --self-contained false -o ./release

      # Create a .tar.gz archive
      - name: Packing archive
        run: tar czvf ./release.tar.gz ./release

      # Create the release
      - name: Create release archive
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload the release
      - name: Upload release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tar.gz
          asset_name: release-${{ github.ref }}-${{ matrix.target }}
          asset_content_type: application/gzip